#!/usr/bin/env python3
# Copyright (C) 2024
# ViliusSutkus89.com
#
# OutputRedirector-Android is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# OutputRedirector-Android is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import getopt
import os
import sys
from version import Versioner


if __name__ == '__main__':
    ci = False
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['ci'])
        for o, a in opts:
            if o == '--ci':
                ci = True
    except getopt.GetoptError as err:
        print(err, file=sys.stderr)
        exit(os.EX_USAGE)

    version = Versioner().version_name
    github_output = os.getenv('GITHUB_OUTPUT', False)
    if ci and github_output:
        with open(github_output, 'a') as outputFile:
            outputFile.write(f'version={version}\n')
    else:
        print(version)
