name: build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SkipCI]')"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "ndk;23.2.8568313"

      - run: ./gradlew lintRelease publishToMavenLocal

      - uses: actions/upload-artifact@v4
        with:
          name: library-lint-report
          path: outputredirector/build/reports/lint-results-release.html
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: maven-local
          path: ~/.m2
          if-no-files-found: error
