name: Build
on: push

env:
  ANDROID_SDK_TOOLS:  "6514223"
  ANDROID_NDK:        "22.0.7026061"
  ANDROID_CMAKE:      "3.10.2.4988404"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache android-sdk.zip
        uses: actions/cache@v1
        with:
          key: android-sdk.zip-${{ env.ANDROID_SDK_TOOLS }}
          path: android-sdk

      - run: .github/installAndroidTools.sh

      - name: Build project
        run: ./gradlew build -PdisablePreDex

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(./getVersion.sh)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: "OutputRedirector-Android v${{ steps.get_version.outputs.version }} - ${{ github.event.commits[0].message }} - ${{ github.ref }}"
          draft: true
          prerelease: false

      - name: Upload Release aar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputredirector/build/outputs/aar/outputredirector-android-release.aar
          asset_name: outputredirector-android-release.aar
          asset_content_type: application/zip

      - name: Upload Debug aar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputredirector/build/outputs/aar/outputredirector-android-debug.aar
          asset_name: outputredirector-android-debug.aar
          asset_content_type: application/zip

      - name: Generate javadoc
        run: ./gradlew outputredirector:javadocJar

      - name: Upload javadoc.jar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputredirector/build/libs/outputredirector-android-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_name: outputredirector-android-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_content_type: application/zip

      - name: Jar the sources
        run: ./gradlew sourceJar

      - name: Upload sources.jar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputredirector/build/libs/outputredirector-android-${{steps.get_version.outputs.version}}-sources.jar
          asset_name: outputredirector-android-${{steps.get_version.outputs.version}}-sources.jar
          asset_content_type: application/zip
