name: Release Publisher

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download assets from this Release
        uses: ViliusSutkus89/release-asset-downloader@v1.0.3
        with:
          outputDirectory: 'releaseAssets'

      - name: Put release assets where gradle would have kept it after the build
        run: |
          mkdir --parents ./outputredirector/build/outputs/aar
          mv ./releaseAssets/outputredirector-android-release.aar ./outputredirector/build/outputs/aar/

          mkdir --parents ./outputredirector/build/libs
          mv ./releaseAssets/outputredirector-android-*-javadoc.jar ./outputredirector/build/libs/
          mv ./releaseAssets/outputredirector-android-*-sources.jar ./outputredirector/build/libs/

      - name: Upload to Bintray
        run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_API_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_API_KEY }}

  versionIncrementer:
    needs: publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: git checkout master

      - run: ./doincrementversion

      - name: git commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Version Incrementer"
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          git add outputredirector/build.gradle

          if git commit -m "PostRelease version increment"
          then
            git push
          fi
